### ISSUE TITLE
リソースファイルの有無で切り替わるファイルが異なる

### ISSUE THREAD

**Issue by smallgeek** [bleis-tift/QuickTestSwitcher#17]
Form1Test.cs から切り替えるとき
Form1.cs と Form1.Designer.cs だけのときは Form1.cs に切り替わる
画像を追加するなどして Form1.resx を生成して切り替えると
Form1.cs ではなく、Form1.resx に切り替わってしまう

**Comment by bleis-tift** [comment]
@smallgeek 修正しました！
